---
title: "Who is likely to churn?"
Author: Emma Wang
---

# Import Libraries 

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(tidymodels)
library(janitor)
```

# Import Data

```{r}
options(scipen = 999)

churn_raw <- read_csv("Churn_training.csv") %>% clean_names()

churn_kaggle <- read_csv("Churn_holdout.csv") %>% clean_names()

churn_raw %>% head()

churn_raw %>% skimr::skim()

```

# Drop Unwanted Variables

```{r}
churn_raw <- churn_raw %>%
  select(-customer_id, -billing_address, -billing_city)
```


# Evaluate Target 

```{r}
churn_summary <- churn_raw %>%
  count(churn) %>%
  mutate(pct = n/sum(n))


churn_summary %>%
  ggplot(aes(x=factor(churn),y=pct)) +
  geom_col()  + 
  geom_text(aes(label = round(pct*100,1)) , vjust = 2.5, colour = "white") + 
  labs(title="Customer Churn", x="Churned", y="PCT")
```

# Change Data Types for Those Necessary

```{r}
churn <- churn_raw %>%
  mutate(yr_month = format(as.Date(customer_reg_date),"%Y-%m"))

churn_kaggle <- churn_kaggle %>%
  mutate(yr_month = format(as.Date(customer_reg_date),"%Y-%m"))

churn$churn <- as.factor(churn$churn)
churn$senior_citizen <- as.character(churn$senior_citizen)
churn$billing_postal <- as.numeric(churn$billing_postal)

churn_kaggle$senior_citizen <- as.factor(churn_kaggle$senior_citizen)
churn_kaggle$billing_postal <- as.numeric(churn_kaggle$billing_postal)

```


# Explore Numeric Variables

```{r}
num_stat <- churn %>%
   pivot_longer(cols = is.numeric, names_to = "column", values_to = "value") %>%
   dplyr::select(column, value) %>%
   group_by(column) %>%
   summarise(count = n(),
             val_miss = sum(is.na(value)),
             n_dis = n_distinct(value),
             mean = mean(value, na.rm = TRUE),
             med = median(value, na.rm = TRUE),
             max = max(value, na.rm = TRUE),
             min = min(value, na.rm = TRUE),
             std = sd(value, na.rm = TRUE)
             )

 num_stat
 
 for (col in num_stat$column){
  box <- churn %>%
  ggplot(aes(x = churn, y  = !!as.name(col))) +
  geom_boxplot()+
  labs(title = paste(col), x = col)
  print(box)
 }
```

# Explore Characteristic Variables

```{r}
char_explore <- function(col){
  
  churn %>%
    ggplot(., aes(!!as.name(col))) + 
    geom_bar(aes(fill = churn), position = "fill")  +
    labs(title = paste("bar-chart of",as.name(col))) +
    theme(axis.text.x = element_text(angle = 45, hjust =1))
    
}


for (column in names(churn %>% select_if (is_character))){
  {
    chrt <- char_explore(column)
    print(chrt)
  }
}
```

# Explore Varaibles 

```{r}
churn %>% skimr::skim_to_wide()
```



# Methodology

## Prepare Data

```{r}
churn_prep <- churn %>% 
   mutate_if(is.character, factor)

churn_kaggle <- churn_kaggle %>% 
   mutate_if(is.character, factor) 
```


## Partition Data

```{r}
set.seed(123)
x <- initial_split(churn_prep, prop = 0.7)
train <- training(x)
test  <- testing(x)
```

## Define Recipe

```{r}
knn_recipe <- recipe(churn ~ monthly_minutes + number_phones + prev_balance + streaming_minutes + phone_area_code + total_billed + email_domain + streaming_plan + mobile_hotspot + paperless_billing + payment_method + wifi_calling_text + multiple_lines + partner + phone_service + ip_address_asn, data=train)%>% 
  step_impute_median(all_numeric_predictors()) %>%
  step_impute_mode(all_nominal_predictors()) %>%
  step_scale(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors()) 


bake(knn_recipe %>% prep(), train, composition = "tibble")
```

## Define Model
```{r}
knn_model <- nearest_neighbor(neighbors = 10) %>%
  set_mode("classification") %>%
  set_engine("kknn")

logistic_model <- logistic_reg() %>%
  set_mode("classification") %>%
  set_engine("glm")
```

## Define Workflow & Fit

```{r}
knn_workflow <- workflow() %>%
    add_recipe(knn_recipe) %>%
    add_model(knn_model) 

knn_fit <- knn_workflow %>%
           fit(data=train)

options(scipen = 999)

logistic_workflow <- workflow() %>%
  add_recipe(knn_recipe) %>%
  add_model(logistic_model)

logistic_fit <- logistic_workflow %>%
            fit(data=train)

tidy(logistic_fit) %>%
  mutate_at(c("estimate", "std.error", "statistic", "p.value"),round, 4)

```

# Evaluate

## KNN Metrics

```{r}

knn_scored_train <- predict(knn_fit, train, type="prob") %>%
    bind_cols(predict(knn_fit, train, type="class")) %>%
    bind_cols(.,train)

knn_scored_test <- predict(knn_fit, test, type="prob") %>%
      bind_cols(predict(knn_fit,  test, type="class")) %>%
      bind_cols(., test) 

options(yardstick.event_first = FALSE)

  knn_scored_train %>% 
    metrics(churn, .pred_1, estimate = .pred_class) %>%
    mutate(part="training") %>%
    bind_rows( knn_scored_test %>% 
                 metrics(churn, .pred_1, estimate = .pred_class) %>%
                 mutate(part="testing") ) %>%
    filter(.metric %in% c('accuracy','roc_auc')) %>%
    pivot_wider(names_from = .metric, values_from=.estimate)
  
knn_scored_train %>%
  precision(churn,.pred_class) %>%
  mutate(part="training") %>%
  bind_rows(
  knn_scored_test %>%
  precision(churn,.pred_class) %>%
    mutate(part="testing") 
  )

knn_scored_train %>%
  recall(churn,.pred_class) %>%
  mutate(part="training") %>%
  bind_rows(
  knn_scored_test %>%
  recall(churn,.pred_class) %>%
    mutate(part="testing") 
  )


knn_scored_train %>%
  conf_mat(
  truth = churn,
  estimate = .pred_class,
  dnn = c("Prediction", "Truth")
) %>%
  autoplot(type = "heatmap") + 
  labs(title="Training Confusion Matrix")

knn_scored_test %>%
  conf_mat(
  truth = churn,
  estimate = .pred_class,
  dnn = c("Prediction", "Truth")
) %>%
  autoplot(type = "heatmap") + 
  labs(title="Testing Confusion Matrix")
```


## Logistic Metrics

```{r}

logistic_scored_train <- predict(logistic_fit, train, type="prob") %>%
    bind_cols(predict(logistic_fit, train, type="class")) %>%
    bind_cols(.,train)

logistic_scored_test <- predict(logistic_fit, test, type="prob") %>%
      bind_cols(predict(logistic_fit,  test, type="class")) %>%
      bind_cols(., test) 

options(yardstick.event_first = FALSE)

  logistic_scored_train %>% 
    metrics(churn, .pred_1, estimate = .pred_class) %>%
    mutate(part="training") %>%
    bind_rows( logistic_scored_test %>% 
                 metrics(churn, .pred_1, estimate = .pred_class) %>%
                 mutate(part="testing") ) %>%
    filter(.metric %in% c('accuracy','roc_auc')) %>%
    pivot_wider(names_from = .metric, values_from=.estimate)
  
logistic_scored_train %>%
  precision(churn,.pred_class) %>%
  mutate(part="training") %>%
  bind_rows(
  logistic_scored_test %>%
  precision(churn,.pred_class) %>%
    mutate(part="testing") 
  )

logistic_scored_train %>%
  recall(churn,.pred_class) %>%
  mutate(part="training") %>%
  bind_rows(
  logistic_scored_test %>%
  recall(churn,.pred_class) %>%
    mutate(part="testing") 
  )


logistic_scored_train %>%
  conf_mat(
  truth = churn,
  estimate = .pred_class,
  dnn = c("Prediction", "Truth")
) %>%
  autoplot(type = "heatmap") + 
  labs(title="Training Confusion Matrix")

logistic_scored_test %>%
  conf_mat(
  truth = churn,
  estimate = .pred_class,
  dnn = c("Prediction", "Truth")
) %>%
  autoplot(type = "heatmap") + 
  labs(title="Testing Confusion Matrix")
  


```




# Kaggle Output

```{r}
knn_scored_churn <- predict(knn_fit, churn_kaggle, type = "class") %>%
  bind_cols(., churn_kaggle)

knn_scored_churn

knn_scored_churn %>%
  select(customer_id, churn = .pred_class) %>%
  write_csv("knn_prediction.csv")

logistic_scored_churn <- predict(logistic_fit, churn_kaggle, type = "class") %>%
  bind_cols(., churn_kaggle)

logistic_scored_churn

logistic_scored_churn %>%
  select(customer_id, churn = .pred_class) %>%
  write_csv("logistic_prediction.csv")
```

